### ISSUE TITLE
如何保存训练好的模型

### ISSUE THREAD

**Issue by Tord-Zhang** [yolomax/person-reid-lib#10]
代码好像默认没有保存训练好的模型？
此外，为啥将网络训练了十次？是进行了交叉验证吗？

**Comment by yolomax** [comment]
请将solver.py中对的[ self.save_model](https://github.com/yolomax/person-reid-lib/blob/15c325aab0b74abc1622040683aa6d6d6ec2f8bb/tasks/task_video/solver.py#L23)设置为True，即可保存模型。

样例代码中给的是iLIDS-VID数据集的，这个数据集需要十次交叉验证。若是想在MARS上测试，可以修改[train_test.py](https://github.com/yolomax/person-reid-lib/blob/15c325aab0b74abc1622040683aa6d6d6ec2f8bb/tasks/task_video/train_test.py#L27) 中选择数据集的那一行，并将重复次数改为1.

**Comment by Tord-Zhang** [comment]
请问PRID数据集需要10次交叉验证吗？

**Comment by yolomax** [comment]
需要的，与iLIDS相同，这两个都是小数据集

**Comment by Tord-Zhang** [comment]
请问图片数据集上，默认的代码是用于训练VIPER的？MARKET1501需要进行10折的交叉验证吗？这个数据集好像有明确分测试机训练集，应该不需要？

**Comment by yolomax** [comment]
你修改一下train_test.py文件中选择数据集ID的那一行就能改数据集了。Market是有固定划分的，不需要交叉验证，你将重复次数改为1就行了。
