### ISSUE TITLE
关于运行问题

### ISSUE THREAD

**Issue by c-dada** [yolomax/person-reid-lib#13]
您好，请问下面几个路径的含义是什么，要怎么设置，数据集需要放在哪里，谢谢。
'root': Path('/home/username/data'),     
'rawfiles': Path('/home/username/rawfiles'), 
'Model': Path('/home/username/model'),  
'web_env_dir': '/home/username/ignore',

**Comment by yolomax** [comment]
在‘’rawfiles‘指定的’原始数据文件夹中，直接放你从网上下载到的数据集的压缩文件。‘root’指定的数据文件夹中是用来存放解压出来的数据的。当代码运行时，code会先去‘root’指定的数据文件夹中找解压出的数据，要是没找到，会自动从‘’rawfiles‘指定的’原始数据文件夹找原始的压缩文件并解压到数据文件夹。所以你可以直接放压缩文件让代码自动处理，也可以解压好直接放到数据文件夹爱。‘’model‘指定的文件夹是用来存放pytorch运行时下载下来的官方预训练的模型文件。web_env_dir这个路径是跟visdom网页可视化有关的，你不需要往这个文件夹里放东西，他只是visdom用来存放可视化数据的文件夹。
