### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 68.00 MiB (GPU 0; 10.76 GiB total capacity; 9.62 GiB already allocated; 34.69 MiB free; 180.72 MiB cached)

### ISSUE THREAD

**Issue by mogeko2333** [yolomax/person-reid-lib#14]
I use '**--gpu=0**' in task_video.sh ,the memory size of my graphics card is **11G**.
**How much video memory does it need to run?**

**Comment by yolomax** [comment]
We use four 1080 Ti GPUs.

**Comment by yolomax** [comment]
try --gpu=0,1,2,3

**Comment by mogeko2333** [comment]
> 我们使用四个1080 Ti GPU。

Thank you for your reply! Is this an absolute requirement？I have only two gpu deveice.

**Comment by yolomax** [comment]
You can reduce the batch size by modifying _instance_num_ in [solver.py](https://github.com/yolomax/person-reid-lib/blob/15c325aab0b74abc1622040683aa6d6d6ec2f8bb/tasks/task_video/solver.py#L10) to adjust the number of pedestrians in a batch to reduce the need for GPU memory. But this can degrade the performances. In general, larger batch size leads to better performance.

**Comment by mogeko2333** [comment]
thank you! I will try！

**Comment by mogeko2333** [comment]
I have some quetions.
1. How to resume training from a saved model? I use '**self.reuse_model = True**' ,but it is not works.
2. How to choose the network to train? I find '**inception_v3**' and '**resnet-50**' in your code.

Thank you for your patience！

**Comment by yolomax** [comment]
A1: Please change the mode to "Test" in [train_test.py.](https://github.com/yolomax/person-reid-lib/blob/15c325aab0b74abc1622040683aa6d6d6ec2f8bb/tasks/task_video/train_test.py#L16). This is the only setting you need to change. 'self.reuse_model = True' is used to load the intermediate model during training. Please set it to default.  The storage location of the model required for testing is the default storage location for training.

A2: Please modify the model in this class ModelClient of architecture.py [architecture.py](https://github.com/yolomax/person-reid-lib/blob/15c325aab0b74abc1622040683aa6d6d6ec2f8bb/tasks/task_video/architecture.py#L70)
