### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by chanajianyu** [yolomax/person-reid-lib#2]
in your sh file , how to train the video datasets?

**Comment by yolomax** [comment]
I have updated the readme. See [how to run.](https://github.com/yolomax/person-reid-lib#how-to-run)

**Comment by chanajianyu** [comment]
howerer, the lastest opencv-python==0.4.0 , the file in lib/dataset/optical_flow_tools.py , in the line 8, 
  TVL1 = cv2.DualTVL1OpticalFlow_create(), it does not work

**Comment by chanajianyu** [comment]
can you share your python , pytorch, opencv-python version?

**Comment by yolomax** [comment]
I have updated the readme. Thanks for your feedback.

**Comment by chanajianyu** [comment]
thank you very much! but , can you show  how to change lr, train_batch_size in the readme?

**Comment by chanajianyu** [comment]
I find how to change in your code, but i think you‘d better show in your readme

**Comment by chanajianyu** [comment]
I don't find how to train on resnet model? the default is Inception_v3
