### ISSUE TITLE
Inception V3  Auxlogits

### ISSUE THREAD

**Issue by SigmaLGX** [yolomax/person-reid-lib#3]
您好，
我已经成功的在MARS以及iLIDS-VID数据集上复现了论文的指标。
但是我对于Inception V3的AuxLogits有些疑问，AuxLogits是固定为768个分类类别，这样在训练iLIDS-VID的150分类时候，起到的作用是什么？

**Comment by yolomax** [comment]
你好，
非常感谢你对我们工作的关注。你反馈的问题已经收到。在我后期整理代码的时AuxLogits中最后的全连接层被删掉了，但是我忘记重新添加新的全连接层了。因为最后一层的特征数比ID数大，所以训练时没有出现报bug，似乎也没有显著影响性能。感谢你的提醒，我已经修正了代码，将此全连接层加了上去。

**Comment by SigmaLGX** [comment]
嗯嗯，我理解错了。 我还以为是Inception的一种辅助机制。

**Comment by SigmaLGX** [comment]
谢谢！
