### ISSUE TITLE
训练、测试输入不同

### ISSUE THREAD

**Issue by SigmaLGX** [yolomax/person-reid-lib#4]
您好，
      我发现task_video在训练时，输入的数据为一个8帧的视频序列。但是在测试时候，输入为一张图片。请问这个会有影响吗？

**Comment by yolomax** [comment]
你好，
非常感谢你对我们工作的关注。在测试的时候，网络会先用backbone模型对一个视频中单张图片提取特征，当所有帧的特征提取完成后才会开始把这些特征一起送到RRU等模块进行融合并得到最后的视频特征表达。这样做主要是因为一次性全部输入所有数据会导致显存不够。

**Comment by SigmaLGX** [comment]
好的，我看到方法了。非常感谢！
