### ISSUE TITLE
Image Resolution

### ISSUE THREAD

**Issue by kerryliu28** [yolomax/person-reid-lib#6]
Hi,

I tried to train the model on relatively small images. I mean some could be 20 * 20. but on average, the image size is around 70 * 70.  The final mAp and Rank1 score was quite disppointing. Even lower than training with single image. I am wondering did you try this model on such tiny images before? I guess the refine unit could have negative impact when resolution was low since after resizing tiny image to 299 * 299, it will be too blur.... May be it's too hard for refine unit to infer any info from such blur one? Any suggestions would be appreciated!

**Comment by yolomax** [comment]
You can replace the backbone model (inception-v3) with a more suitable one, which has a smaller input image size.

**Comment by kerryliu28** [comment]
Thx I will. I have tried some much smaller LRs, the training process looks much better so far. the default 0.01 for new params and 0.01*10 for base model may be too big for such task.
