### ISSUE TITLE
lmdb加载mars数据太久了

### ISSUE THREAD

**Issue by qianjinhao** [yolomax/person-reid-lib#7]
lmdb加载mars数据太久了，过了一个多小时连第一个id的图片都没加载完

**Comment by yolomax** [comment]
第一次生成lmdb的时候会比较慢，创建完之后，以后就是直接读取lmdb文件，速度就快了。

**Comment by qianjinhao** [comment]
> 第一次生成lmdb的时候会比较慢，创建完之后，以后就是直接读取lmdb文件，速度就快了。

第一次mars数据集加载大概要多久？我想有个参考

**Comment by yolomax** [comment]
总时长取决于你的服务器性能。我的一个晚上是够的，具体多少时间不记得了。
