### ISSUE TITLE
prid2011 and ilidsvid 数据集问题

### ISSUE THREAD

**Issue by MeaninglessAI** [yolomax/person-reid-lib#8]
作者您好，在阅读你代码的时候，在数据集处理相关代码中，具体为prid2011 .py 和 ilidsvid.py 这两个文件中，都有对数据集划分的.mat文件，分别为train_test_splits_prid.mat 和 train_test_splits_ilidsvid.mat 请问这两个.mat文件如何获得呢？

**Comment by yolomax** [comment]
http://www.eecs.qmul.ac.uk/~xiatian/iLIDS-VID/iLIDS-VID.tar

谢谢你对我们工作的关注。上面这个链接里面的数据集下载下来之后，解压文件，里面有你需要的mat文件。

**Comment by MeaninglessAI** [comment]
感谢解答
