### ISSUE TITLE
RRU+STIM

### ISSUE THREAD

**Issue by donghaiwang** [yolomax/person-reid-lib#9]
您好，在这个项目底下似乎没有找到论文《Spatial and Temporal Mutual Promotion for Video-based Person Re-identification》所对RRU和STIM所对应的代码，另一个项目https://github.com/yolomax/rru-reid 也是不完整的，请问有没有整合进来相关的代码，谢谢~

**Comment by yolomax** [comment]
感谢对我们工作的关注。RRU与STIM的代码请参见 [https://github.com/yolomax/person-reid-lib/blob/15c325aab0b74abc1622040683aa6d6d6ec2f8bb/tasks/task_video/architecture.py#L9](url)
